export const INITIATE_APP = 'INITIATE_APP';
export const SET_INITIATE_APP = 'SET_INITIATE_APP';
export const INITIATE_APP_ERROR = 'INITIATE_APP_ERROR';

export const FLIP = 'FLIP';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const UPDATE_SCORES = 'UPDATE_SCORES';
export const RESET_LAST_ANSWER = 'RESET_LAST_ANSWER';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const SET_NEXT_QUESTION = 'SET_NEXT_QUESTION';
